# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 3ccf4c9f00c5d5cc661426fb84b619e09ac3eae8219f8ed47902b276bc3005b6e24717fad077502dde5c9f8ea2f51cb5205896ad42c433c8505d0e661683731a

test:
  secret_key_base: 8252259d51dbbe9e41075228d3a9a46bc0f40e9a9e384708c7aa6d5f6dab8992ff570c4f33a083d2a3d4cf456d818b7cf45f1ce42c850a8ffc5c6094e6c30c08

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
